### ISSUE TITLE
Chromote timeout leads to selenider error when connecting to some insecure website

### ISSUE THREAD

**Issue by sybrohee** [ashbythorpe/selenider#16]
It might happen that, when connecting to a website where the certificate in not completely secure, chrome takes some time to display the page and chromote returns an error when using default parameters as the timeout value is reached.

https://github.com/rstudio/chromote/issues/152

`b$Page$navigate("https://my/insecure/app")`

To circumvent this, in chromote, we can use the parameters timeout.

`b$Page$navigate("https://my/insecure/app", timeout = 50000)`

However, this feature is not available in selenider through the command selenider::open_url(). Although, we can use chromote to connect to the page, and the use selenider once the website has been reached, it would be nice to have everything working with selenider by adding a timeout parameter to the open_url function.

For the moment, this is the way I reach my insecure website page 

```
    temp_file <- tempfile(pattern = "mychrome", fileext = ".sh", tmpdir = Sys.getenv("HOME"))
    writeLines(c("#!/bin/bash", '/usr/bin/google-chrome  --ignore-certificate-errors  "$@"'), con = temp_file)
    system(paste0("chmod +x ", temp_file))
    myurl <- "https://my/insecure/app"
    chromote <- Chromote$new(browser = Chrome$new(path = temp_file)) 
    my_chromote_object <- chromote::ChromoteSession$new(parent = chromote, height = 1080, width = 1920)
    mySeleniderSession <- selenider::selenider_session(
        driver = my_chromote_object,
        view = F
    )
    promise <- mySeleniderSession$driver$Page$loadEventFired(wait_ = FALSE, timeout_ = 60)
    mySeleniderSession$driver$Page$navigate(myurl , wait_ = FALSE, timeout = 50000)
    mySeleniderSession$driver$wait_for(promise)
```

**Comment by ashbythorpe** [comment]
I've now added a `timeout` option to `open_url()`, `back()`, `forward()`, and `reload()`/`refresh()` in the dev version of selenider. Hopefully this fixes your problem.

**Comment by sybrohee** [comment]
Cool. You are my new hero : I will test that in the coming days.

**Comment by markwsac** [comment]
Thanks for this awesome package. The timeout argument is really helpful not just for insecure website but also for websites with ads. Websites with ads take a lot of time to load. Hence, the `open_url()` without timeout argument fails in 6 out of 10 times. Can you release this version in the CRAN please as I can't download the package from github in my workplace?

**Comment by ashbythorpe** [comment]
Sure, I'd be happy to prepare a release, probably by the end of the week. Also, you can download the development version from R-universe, if that works better for you:
https://ashbythorpe.r-universe.dev/selenider

**Comment by markwsac** [comment]
Thank you. Would be great by the end of the week. Also I noticed chrome browser shuts down automatically after inactivity of 60 seconds. Can we increase the duration before it shuts down?
```
library(selenider)
session <- selenider_session("selenium", browser = "chrome")
```

**Comment by ashbythorpe** [comment]
Hi, sorry, I forgot about this issue for a while.

selenider 0.4.0 released a while ago (hopefully you saw that?).

To solve your issue, something like this should work (see https://www.selenium.dev/documentation/grid/configuration/cli_options/):

``` r
session <- selenider_session("selenium", options = selenium_options(
  server_options = selenium_server_options(
    extra_args = c("--session-timeout", "3000")
  )
))
```

**Comment by sybrohee** [comment]
> I've now added a `timeout` option to `open_url()`, `back()`, `forward()`, and `reload()`/`refresh()` in the dev version of selenider. Hopefully this fixes your problem.

Hi, I just (finally) tested it ... it works great and it is way better than my awful hack. Thank you for everything.
