### ISSUE TITLE
Get All Cookies with selenider

### ISSUE THREAD

**Issue by awosoga** [ashbythorpe/selenider#18]
Is there a selenider equivalent to RSelenium's `getAllCookies()`?

**Comment by ashbythorpe** [comment]
If you are using chromote (the default), you can use [Storage.getCookies](https://chromedevtools.github.io/devtools-protocol/tot/Storage/#method-getCookies):

``` r
library(selenider)

session <- selenider_session()

session$driver$Storage$getCookies()
```

If you are using selenium, you can use [`SeleniumSession$get_cookies()`](https://ashbythorpe.github.io/selenium-r/reference/SeleniumSession.html#method-SeleniumSession-get_cookies):

``` r
library(selenider)

session <- selenider_session("selenium")

session$driver$get_cookies()
```

**Comment by awosoga** [comment]
excellent, thank you!
