### ISSUE TITLE
Parallel webscraping

### ISSUE THREAD

**Issue by mariusgordan** [ashbythorpe/selenider#20]
Hello, is it possible to webscrape in parallel, perhaps using the parallel and foreach?

**Comment by ashbythorpe** [comment]
I tested with a simple script, which seemed to work fine:

``` r
library(foreach)
library(doParallel)

scrape <- function() {
  library(selenider)

  session <- selenider_session()

  open_url("https://r-project.org")

  s("*") |>
    elem_text()
}

cluster <- makeCluster(4)
registerDoParallel(cluster)
foreach(i = 1:10) %dopar% scrape()
```

If you're using selenium, you should be able to share the server between threads, since the server can handle multiple clients at once (I don't know whether this will make things faster or slower).

``` r
library(foreach)
library(doParallel)
library(selenium)

server <- selenium_server(interactive = FALSE)

scrape <- function() {
  library(selenider)

  session <- selenider_session("selenium", options = selenium_options(server_options = NULL))

  open_url("https://r-project.org")

  s("*") |>
    elem_text()
}

cluster <- makeCluster(4)
registerDoParallel(cluster)
foreach(i = 1:10) %dopar% scrape()
```

**Comment by mariusgordan** [comment]
Thank you for the support! I noticed that when I use ss() %>% rvest::read_html() I get the following error:
>no applicable method for 'read_xml' applied to an object of class "c('selenider_elements', 'list')"
This does not happen when I use read_html() with s(), so I found this workaround:
```
parse_text <- function(x) {
    read_html(x) %>%
      html_text2
  }
sapply(ss('css.selector'), parse text)
```
However, this is quite slow. Any tips on how to solve this?

**Comment by ashbythorpe** [comment]
Yeah, switching to static HTML at an earlier stage will usually be faster.
