### ISSUE TITLE
Error in utils::download.file(url, path, quiet= !verbose)

### ISSUE THREAD

**Issue by hassaanuh** [ashbythorpe/selenider#29]
Unable to initiate selenium session!

cannot open URL 'https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.25.0/selenium-server-4.25.0.jar'
In addition: Warning message:
In utils::download.file(url, path, quiet = !verbose) :
  cannot open URL 'https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.25.0/selenium-server-4.25.0.jar': HTTP status was '404 Not Found'

**Comment by ashbythorpe** [comment]
Looks to be a duplicate of #27. Try downloading the development version of selenium (`pak::pak("ashbythorpe/selenium-r")`) and see if that fixes things.

**Comment by hassaanuh** [comment]
Thank you!


It worked
