### ISSUE TITLE
How to use elem_scroll_to in selenider to scroll down to the bottom of a long html/xml document

### ISSUE THREAD

**Issue by SugarRayLua** [ashbythorpe/selenider#38]
Hi, and thanks for developing this great package! I'm a novice webscraper and like how intuitive the functions in selenider are named.

However, I'm currently attempting to scrape a website that loads more data as one scrolls down the page. Therefore, when I attempt to ss(elements) without having selenider scroll the page then I don't retrieve all the data that I want. I read that the solution is to then to have one's webscraper program scroll down to the bottom of the html/xml document first which would then load the entire html/xml then use the webscraper program (e.g. selenider) to extract the elements I'm looking for. 

The documentation of elem_scroll_to specifically illustrates how to scroll to a known element; however, I couldn't figure out how to get selenider to though scroll to the bottom of any html/xml page if one doesn't not know the last element a priori. I tried:

elem_scroll_to(s(xpath="//div[last()]")) but that didn't seem to work.

I saw though that it is possible to use javascript with this command and further read that with javascript one can select document.body.scrollHeight to accomplish such scrolling to the end of a long html/xlml document but didn't know how to tie that all together to make it work in selenider.

I would appreciate any help you could provide.

Thank you!

**Comment by ashbythorpe** [comment]
Right now selenider doesn't have a dedicated function for scrolling, although one might be added.

However, if you've found some JavaScript that will work, `execute_js_expr()` will do what you want:

``` r
execute_js_expr("window.scrollTo(0, document.body.scrollHeight);")
```

**Comment by SugarRayLua** [comment]
Thank you, @ashbythorpe :-)
